<?php

function csv_import_menu() {
  $items['/admin/config/csv_import'] = array(
    'title' => 'Importer list',
    'route' => 'csv_import_root',
  );
  $items['/admin/config/csv_import/add'] = array(
    'title' => 'Add csv importer',
    'route' => 'csv_import_add',
  );
  $items['/admin/config/csv_import/list/%'] = array(
    'title' => 'List Mapping fields of CSV importer',
    'route' => 'csv_import_list_fields',
  );
  $items['/admin/config/csv_import/list/%/add'] = array(
    'title' => 'Add fields in importer',
    'route' => 'csv_importer_add_fields',
  );
  $items['/admin/config/csv_import/list/%/delete/%'] = array(
    'title' => 'delete fields in importer',
    'route' => 'csv_importer_delete_fields',
  );
  $items['/admin/config/csv_import/list/%/edit/%'] = array(
    'title' => 'Edit field in importer',
    'route' => 'csv_importer_edit_fields',
  );
  $items['/admin/config/csv_import/delete/%'] = array(
    'title' => 'Delete importer',
    'route' => 'csv_delete_importer',
  );
  $items['/admin/config/csv_import/import'] = array(
    'title' => 'Import content',
    'route' => 'import_content',
  );
  return $items;
}