<?php

/**
 * Implements hook_menu().
 */
function csv_import_menu() {
  $items['/admin/config/development/csv_import'] = array(
    'route' => 'csv_import_root',
  );
  $items['/admin/config/development/csv_import/add'] = array(
    'route' => 'csv_import_add',
  );
  $items['/admin/config/development/csv_import/list/%'] = array(
    'route' => 'csv_import_list_fields',
  );
  $items['/admin/config/development/csv_import/list/%/add'] = array(
    'route' => 'csv_importer_add_fields',
  );
  $items['/admin/config/development/csv_import/list/%/delete/%'] = array(
    'route' => 'csv_importer_delete_fields',
  );
  $items['/admin/config/development/csv_import/list/%/edit/%'] = array(
    'route' => 'csv_importer_edit_fields',
  );
  $items['/admin/config/development/csv_import/delete/%'] = array(
    'route' => 'csv_delete_importer',
  );
  $items['/admin/config/development/csv_import/import/%'] = array(
    'route' => 'import_content',
  );
  $items['/admin/config/development/csv_import/edit/%'] = array(
    'route' => 'edit_importer',
  );
  $items['/admin/config/development/csv_import/list/%/field_processor'] = array(
    'route' => 'csv_field_processor',
  );
  $items['/admin/config/development/csv_import/list/%/add_processor/%'] = array(
    'route' => 'csv_add_field_processor',
  );
  $items['/admin/config/development/csv_import/list/%/delete_processor/%'] = array(
    'route' => 'csv_field_processor_delete',
  );
  $items['/admin/config/development/csv_import/list/%/edit_processor/%'] = array(
    'route' => 'csv_edit_field_processor',
  );
  return $items;
}